version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:18.13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths: 
            - node_modules

  build:
    docker:
      - image: cimg/node:18.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: cimg/node:18.13
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys:
          fingerprints:
            - "SHA256:gySqaXDZh9bK2gTYDA2kI+Nz8U8QBqYq8PstDZ2ynOc"

      - run:
          name: Deploy to Amazon EC2 instance
          command: |
            scp -o StrictHostKeyChecking=no -r dist/ ubuntu@ec2-13-49-76-13.eu-north-1.compute.amazonaws.com:/var/www/html

workflows:
  version: 2
  deploy_fe:
    jobs:
      - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build